### ISSUE TITLE
Question: Supporting pull requests across forks?

### ISSUE THREAD

**Issue by krancour** [brigadecore/brigade-bitbucket-gateway#10]
When I open a new pull request from a fork, my gateway receives the `pullrequest:created` event and emits it into Brigade and it triggers a build...

But the vcs-sidecar (it's an init container, really) on the worker fails to obtain the source tat it should build. Errors for that container indicate the ref (branch) does not exist in the repository... but it looks like it's trying to get it from the _target repo_ instead of the source repo.

I'll dig deeper to try to pinpoint the source of the problem, but I'm at least curious whether pull requests across forks was intended to be supported or whether this might be an oversight or an operator error.

**Comment by krancour** [comment]
Just found this in your docs:

> The Pull Request events are questionable to support, please open an issue if you have any use-case issues.

Maybe that answers my question.

I'll see what I can do about fixing this.

**Comment by krancour** [comment]
The trick here would be to get the gateway to set information about the source repository in the event/build that it emits into Brigade. This isn't currently possible, but I have proposed a change to Brigade itself to facilitate that. See https://github.com/brigadecore/brigade/issues/973.

**Comment by krancour** [comment]
https://github.com/brigadecore/brigade/pull/975 paves the way for a fix here. As soon as that is merged, I have a PR for the bb gateway. 😄

**Comment by lukepatrick** [comment]
Thanks for looking. I haven't had the use case yet, but trying figure out _which_ repo to build from was tbd. Assume this will be configurable by the user whether they want to allow their brigade to build everyone's fork's?

**Comment by krancour** [comment]
> Assume this will be configurable by the user whether they want to allow their brigade to build everyone's fork's?

I suppose that is something that would have to be added. The GitHub gateway lets you configure what user roles are whitelisted to trigger builds from their PRs. We'd have to add something like that here as well, I believe.

**Comment by krancour** [comment]
Well... that last bit seems easier said than done. I've just been dissecting some webhook payloads, and unlike in the case of GitHub, there's nothing that describes the PR author's role WRT the repo the PR was opened against.

**Comment by krancour** [comment]
https://community.atlassian.com/t5/Bitbucket-questions/Differentiating-trusted-v-non-trusted-actors-in-webhooks/qaq-p/1154238#M45542

**Comment by krancour** [comment]
It seems the best we may be able to do here is make a list of trusted users configurable at either the gateway level or project level. (Project level would be better.)

In either case, this looks kind of ugly. Updating the list of trusted users at the gw level would involve `helm upgrade` and updating the list of trusted users at the project level would require `brig project create --replace` (or manually tampering with the project secret).

Something else that makes this ugly is that usernames (or "nicknames" as BB calls them) are mutable. To be truly secure here, the list of trusted users would need to be composed of immutable IDs. We could use a scheme something like `<id:nickname>` so that each entry is effectively "commented" (comments are otherwise not possible in JSON).

None of this looks great, so far, but here's the nicer part...

Besides suppressing builds triggered by untrusted users, we can build support for trusted users to trigger a build of a given PR via a `/brig run` comment. (This is a new feature that is already planned for the github gateway, so there would be some nice parity there.)

@lukepatrick let me know what you think.

**Comment by krancour** [comment]
I've concluded that at present, Bitbucket simply doesn't include an adequate degree of metadata in the the webhooks to ascertain a fork owner's relationship to the upstream repository and whether they are or are not authorized to trigger a build. This shouldn't be interpreted as any indictment of Bitbucket in terms of a feature that is lacking. I think the more likely explanation here is that I'm trying to map a common GitHub workflow/paradigm onto Bitbucket, which likely has its own preferred or suggested way of doing these things, which I am probably not adequately informed of. Long story short-- I'm going to close this.
