### ISSUE TITLE
Main process error

### ISSUE THREAD

**Issue by droman08** [brigadecore/brigade-bitbucket-gateway#11]
Hello

I have deployed the bitbucket gateway in Azure AKS environment but when I execute the call it is returning an error which I detail below:

`2019/09/24 01:36:47 INFO: Listening on addr: :7748 path: /events/bitbucket
2019/09/24 01:40:36 INFO: Webhook received
2019/09/24 01:40:36 INFO: Parsing Payload...
2019/09/24 01:40:36 HandleMultiple Payload..
2019/09/24 01:40:36 case bitbucket.RepoPushPayload
panic: runtime error: index out of range
`
`bash
goroutine 103 [running]:
main.HandleMultiple(0xf23600, 0xc420094200, 0xc4201ccfc0)
        /Users/luke/go/src/github.com/lukepatrick/brigade-bitbucket-gateway/brigade-bitbucket-gateway/cmd/brigade-bitbucket-gateway/server.go:108 +0x31e6
github.com/lukepatrick/brigade-bitbucket-gateway/vendor/gopkg.in/go-playground/webhooks.v3/bitbucket.Webhook.runProcessPayloadFunc.func1(0x10593f0, 0xf23600, 0xc420094200, 0xc4201ccfc0)
        /Users/luke/go/src/github.com/lukepatrick/brigade-bitbucket-gateway/vendor/gopkg.in/go-playground/webhooks.v3/bitbucket/bitbucket.go:197 +0x44
created by github.com/lukepatrick/brigade-bitbucket-gateway/vendor/gopkg.in/go-playground/webhooks.v3/bitbucket.Webhook.runProcessPayloadFunc
        /Users/luke/go/src/github.com/lukepatrick/brigade-bitbucket-gateway/vendor/gopkg.in/go-playground/webhooks.v3/bitbucket/bitbucket.go:196 +0x5d`

### Calls's Details:
=============
`
curl -vk -H "X-Hook-Uuid:Uwm2p" -H "X-Event-Key:repo:push" -X POST https://<domain>/events/bitbucket -d @payload-brigade.json
`
### payload-brigade.json
===============
`json
{"eventKey":"repo:push","date":"2019-09-23T18:36:57-0500","actor":{"name":"XXXX","emailAddress":"prueba@abc.com.pe","id":44152,"displayName":"Usuario Prueba","active":true,"slug":"XXXX","type":"NORMAL"},"repository":{"slug":"properties-test-brigade","id":3677,"name":"properties-test-brigade","scmId":"git","state":"AVAILABLE","statusMessage":"Available","forkable":true,"project":{"key":"~XXXX","id":566,"name":"Usuario Prueba","type":"PERSONAL","owner":{"name":"XXXX","emailAddress":"prueba@abc.com.pe","id":44152,"displayName":"Usuario Prueba","active":true,"slug":"s83012","type":"NORMAL"}},"public":false},"changes":[{"ref":{"id":"refs/heads/prueba-deploy","displayId":"prueba-deploy","type":"BRANCH"},"refId":"refs/heads/prueba-deploy","fromHash":"28c73a4c5b167ar8u59e1106696bc19ec6fb4355","toHash":"222e71bb1aac482a96aca1477d7jhc6242c020cb","type":"UPDATE"}]}
`

**Comment by krancour** [comment]
Closing due to staleness. Please do reopen if necessary.
