### ISSUE TITLE
Passing request headers to workers and jobs

### ISSUE THREAD

**Issue by Strandedpirate** [brigadecore/brigade-bitbucket-gateway#5]
I'm creating a custom UI on top of brigade for my company that spans many projects and would like more details about each bitbucket request (headers). (I'm aware of kashti but it is a no-go for us.)

Requesting that headers sent by bitbucket be stored in the secrets and passed to the worker and jobs. This information can then be used in our database as primary keys and for tracking purposes.

Headers:
```
X-Request-UUID                494d26ff-37a7-46d0-aa4e-9518a6b3cf37
User-Agent                        Bitbucket-Webhooks/2.0
X-Attempt-Number           1
X-Hook-UUID                     3a3a6d73-2ce4-4035-9f65-f76af6d2fea2
```

**Comment by krancour** [comment]
Closing due to staleness. Please do reopen if necessary.
