### ISSUE TITLE
How to extract the X-Hook-UUID header

### ISSUE THREAD

**Issue by floriankoch** [brigadecore/brigade-bitbucket-gateway#6]
Hi, i have trouble to find the X-Hook-UUID ,there is no X-Hook-UUID header in the request
I have an local bitbucket server , version 5.10

Any hints how i can find and send this?

**Comment by lukepatrick** [comment]
Where I've seen this is in my Bitbucket Repo -> **Settings** -> **Webhooks** -> Look for the row for the webhook you created for Brigade and click **View requests** -> look under the webhook request logs and select **View details** of an event -> scroll to the bottom, under Requests, Headers, see X-Hook-UUID

**Comment by floriankoch** [comment]
@lukepatrick   i only see these Headers in my bitbucket server

> X-Hub-Signature: sha256=76bcc4377035f766dd236a031f6ec37fbdf14c4b8c3d9cea7bc3d633411af895
> X-Request-Id: 24182101-4de0-4279-98d2-c9fa11fed89e
> Content-Type: application/json; charset=utf-8
> X-Event-Key: repo:refs_changed

**Comment by lukepatrick** [comment]
@floriankoch thanks for pointing this out. It looks like BitBucket Cloud/DC and Server are different products with different webhook API's. The gateway is currently configured to use the Cloud API. An enhancement will need to be made for the Server version.

**Comment by krancour** [comment]
Closing due to staleness. Please do reopen if necessary.
