### ISSUE TITLE
Approve brigade-bitbucket-gateway ownership change

### ISSUE THREAD

**Issue by lukepatrick** [brigadecore/brigade-bitbucket-gateway#7]
Hello All. Exciting news in the world of Brigade, it has recently been accepted to [CNCF as a Sandbox prohect](https://www.cncf.io/sandbox-projects/). Brigade core is moving to the CNCF organization which means CNCF becomes the owner of the code. 

I have been invited to move my Brigade-related projects into the new BrigadeCore organization, which would include transferring this repo to BrigadeCore and ownership to CNCF. As I have accepted Pull Requests from others, I am asking for their ok to change ownership of this repo. 

Please let me know if you have any concerns
@nikolauska

**Comment by nikolauska** [comment]
You have my approvement.
