### ISSUE TITLE
Error in ingress.yaml causes chart to fail if ingress specified

### ISSUE THREAD

**Issue by LittleColin** [brigadecore/brigade-bitbucket-gateway#9]
Looks like ingress.yaml is:
```
{{- $serviceName := include "brigade.gw.fullname" . -}}
{{- $servicePort := .Values.service.externalPort -}}
```
But should be:

```
{{- $serviceName := include "brigade.bitbucket.fullname" . -}}
{{- $servicePort := .Values.bitbucket.service.externalPort -}}
```
Verify with:
`helm upgrade --namespace myns --set ingress.enabled=true --set ingress.hosts[0]="mygateway.com" --set ingress.tls[0].hosts[0]="mygateway.com" --set bitbucket.service.externalPort=7748 --set bitbucket.service.type=ClusterIP --set rbac.enabled=true --install my-bbgw .\charts\brigade-bitbucket-gateway\`

**Comment by krancour** [comment]
Closing due to staleness. Please do reopen if necessary.
